version: '3'


services:
  api:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8091:8080"

  ui:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      - API_URL=http://api:8080
    ports:
      - "8092:80"