version: '3'


services:
  api:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8091:8080"

  ui:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://api:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.pool_rankings.rule=Host(`pool.bar.local`)
      - traefik.http.routers.pool_rankings.entrypoints=web
    ports:
      - "8092:80"